global.lives = 3
global.coin = 0
global.weapon = 0
global.kick = 0
global.weapon_gun = 0
global.weapon_sword = 0
global.hp= 100
global.energy = 100
global.bullet = 20
global.key_1 = 0
global.key_2 = 0